
collections_dir: all_collections

future: true

keep_files: ['node_modules/']
unpublished: true

collections:
  authors:
    layout: front
    output: true

  news: 
    layout: front 
    output: true

  faq:
    layout: front
    output: true  
  
  jobs:
    layout: front
    output: true 
  
  guides:
    layout: front
    output: true

  documents:
    layout: front
    output: false
    
  resources:
    layout: front
    output: false


defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude :
 - node_modules/      

include: ["node_modules"]
exclude: []

# Site settings
title: "Build the Permanent Record | Koii"
description: "Koii was founded on fairness, trust, and one immense objective: to give creators a space where they permanently own and earn the value they deserve from their content." # this means to ignore newlines until "baseurl:"
url: "https://koii.network/" # the base hostname & protocol for your site

twitter_username: KoiiNetwork

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag